Approve calc
sarcaustech/unifac pull request #8
Opened 2020-11-01 13:15 UTC by sarcaustech

Waiting on PR #7 

Overall approving of the calculation so far.

**In scope:**
- Correctness / accuracy
- Tests & test coverage
- Unified coding style

**Out of scope:**
- Compiler warnings
- Public / not public
- Concurrency

2020-11-01 14:48 UTC, sarcaustech reviewed
Think we should talk about a general approach of error handling / propagation, no?
https://yaah.dev/building-your-own-error-type

2020-11-01 14:48 UTC, sarcaustech commented on src/calculator.rs
> +    let mut psi_m_k = Vec::new();
What's the difference between `psi_n_m` and `psi_m_k`? Is it the same matrix, but stored row-wise and col-wise?

2020-11-01 14:48 UTC, sarcaustech commented on src/calculator.rs
> +            if fg_ids.contains(id) {
`shadow` is used to select functional groups of a substance from the overall calced vectors, right? What about not working with bool but setting `1.0` and `0.0`. Then you can remove the `if` statement and simply multiply. Not sure if that's better, but I find the bool `shadow` hard to understand in the first place.

2020-11-01 14:48 UTC, sarcaustech commented on src/calculator.rs
> +            if fg_ids.contains(id) {
Never mind, saw the Doc in #7, should be fine then

2020-11-01 14:48 UTC, sarcaustech commented on src/calculator.rs
> +            let index = id_list.iter().position(|&x| x == fg.id).unwrap();
Would like to get rid of that `unwrap()`, too. Any idea?
Issue: `index` is not the index in `&substances[i].functional_groups`

2020-11-01 14:48 UTC, sarcaustech commented on src/calculator.rs
> +        let sum_1 = formula::calc_11_sum_1(&theta_k, &psi_m_k[i], &vec![false; id_list.len()]);
Needed a moment to understand what's happening. Would prefer a comment why we use those `&vec![false; id_list.len()]` here

2020-11-01 14:48 UTC, sarcaustech commented on src/formula.rs
> +pub fn calc_7(id: u8, sum: f64, substances: &Vec<Substance>) -> f64 {
So far, sums are always the last function parameter. Would like to keep it that way

2020-11-01 14:48 UTC, sarcaustech commented on src/formula.rs
> +        let fg = FunctionalGroup::from(*id, 0.0).unwrap();
Here's another `unwrap()`. Can we pass the whole `FunctionalGroup` with the `HashMap` to avoid this? Another way would be to change to `Result` as return type and propagate with `?`, but I'd also prefer to get all necessary values by function parameters and not calling any `::from` to not couple tight. What do you think?

2020-11-01 14:48 UTC, sarcaustech commented on src/formula.rs
> +pub fn calc_10(i: u8, j: u8, temperature: f64) -> Result<f64, &'static str> {
See `calc_8_sum`

2020-11-01 14:48 UTC, sarcaustech commented on src/formula.rs
> +    if i_maingroup == j_maingroup {
This is code duplication! "`if i == j then 1`" is also part of `calculator.rs`:
```
if id_n == id_m {
    temp.push(1.0);
} else {
    temp.push(formula::calc_10(*id_n, *id_m, temperature).unwrap());
}
```

I guess keeping it here and removing it in `calculator.rs` is the way to go, no?

2020-11-01 14:48 UTC, sarcaustech commented on src/formula.rs
> +    Ok(std::f64::consts::E.powf(-interp.a_ij / temperature))
We might think about input validation (though `T = 0 K` does not make any sense when talking about fluids)

2020-11-01 14:48 UTC, sarcaustech commented on src/formula.rs
> +pub fn calc_12(q_k: f64, sum_1: f64, sum_2: f64) -> f64 {
Like this in first place, but I guess we can remove this one and directly call `calc_11`. Or maybe, do you know if the compiler optimises this anyways?

2020-11-01 14:48 UTC, sarcaustech commented on src/formula.rs
>  }
Currently, we have `calc_14` implemented in `calculator.rs` as `calc`. What to you think about moving?

2020-11-01 14:48 UTC, sarcaustech commented on src/formula.rs
> +
Tests missing

2020-11-09 19:38 UTC, heringerp commented on src/formula.rs
> +        let fg = FunctionalGroup::from(*id, 0.0).unwrap();
Uncoupling the whole thing would be definitely nice. However, the id the function gets stems from `id_list` and is therefore not associated with any already existing functional group, but instead a type of functional group. One possibility would be to have the from statements once at the beginning of `calc_residual()` in `calculator.rs`. This would require a large structural change and would couple `FunctionalGroup` to `calculator.rs` instead. Is that worth it?

2020-11-09 19:38 UTC, heringerp commented on src/formula.rs
> +    Ok(std::f64::consts::E.powf(-interp.a_ij / temperature))
In the `calc_10()` procedure? The other arguments aren't validated either, so does it make sense to have this inconsistency?

2020-11-09 19:38 UTC, heringerp commented on src/formula.rs
>  }
I think moving it to `calc_14` in `formula.rs` would be overkill, since 14 is only one addition.

2020-11-09 19:38 UTC, heringerp commented on src/formula.rs
> +pub fn calc_12(q_k: f64, sum_1: f64, sum_2: f64) -> f64 {
Unsure about the optimization, I'm just removing it

2020-11-09 19:38 UTC, heringerp commented on src/calculator.rs
> +    let mut psi_m_k = Vec::new();
Yes. Renamed it for more clarification

2020-11-10 08:33 UTC, heringerp requested changes

2020-11-10 08:33 UTC, heringerp commented on src/calculator.rs
> +        assert!(true);
Does this function really need to be here? Isn't even a test. Maybe some remnant of the development process?

2020-11-10 08:33 UTC, heringerp commented on src/formula.rs
> +        };
What do you think about moving creation of substances to its own helper function (for all test cases)? Would definitely remove some duplication

2020-11-14 10:44 UTC, sarcaustech commented on src/calculator.rs
> +        assert!(true);
Re-inserted when merging #7 (build error). Removed.

2020-11-14 10:47 UTC, sarcaustech commented on src/calculator.rs
> +    let mut id_list = Vec::new();
All `println!` removed

2020-11-14 10:54 UTC, sarcaustech commented on src/calculator.rs
> +        let mut x_ki_map: HashMap<u8, f64> = HashMap::new();
Changed

2020-11-14 10:59 UTC, sarcaustech commented on src/calculator.rs
> +    println!("r_i: {:?}", r_i);
Removed all `println`

2020-11-14 11:04 UTC, sarcaustech commented on src/formula.rs
> +        let fg = FunctionalGroup::from(*id, 0.0).unwrap();
I see your point. Maybe just move the re-init of the functional groups to `calculator.rs` instead of the formula? 

E.g. see `calc_8` and `calc_8_sum` to which you currently pass `x_k` incl the ids. Then, in both methods, the same groups are re-initialised. When re-initing in `calculator.rs`, we would not need this

2020-11-14 11:06 UTC, sarcaustech commented on src/formula.rs
> +    if i_maingroup == j_maingroup {
What do you think about this? I guess I have to revise myself: Imo, the best way is to have this in `FunctionalGroup::from`

2020-11-14 11:09 UTC, sarcaustech commented on src/formula.rs
> +    Ok(std::f64::consts::E.powf(-interp.a_ij / temperature))
I thought about validation prior to triggering any calculation, so as a very first action. To be checked
- T > 0
- All substance fractions sum up to 1 (not sure if error or warning and recalc fractions)
- No substance without group

(Just first thoughts, might be more)

2020-11-14 11:10 UTC, sarcaustech commented on src/formula.rs
>  }
Fine

2020-11-14 11:13 UTC, sarcaustech commented on src/formula.rs
> +        };
I'm fine with this, but we have to make sure that this is only compiled for testing and not in a release candidate. Do you already have an idea of this?

2020-11-14 11:57 UTC, sarcaustech commented on src/calculator.rs
> +    let x_k_map: HashMap<u8, f64> = id_list.clone().into_iter().zip(x_m).collect();
Not sure if there's an overhead when using `HashMap`, so I removed them. Rewrote without changing logic. Maybe, choosing other arguments (not the `Vec`s but the needed values) is more performant? 

Used `.clone()` all the way, **we'd take a look at borrowing instead when implementing concurrency**.

See 83f198d05fb67f3743d47c53c605ac6f429600ac

2020-11-16 14:52 UTC, heringerp commented on src/formula.rs
> +    Ok(std::f64::consts::E.powf(-interp.a_ij / temperature))
But then at the beginning of `calc()` in `src/calculator.rs`, right?

2020-11-16 14:52 UTC, heringerp commented on src/formula.rs
> +        };
Just leaving it in this very module should achieve this. `#[cfg(test)]` ensures the whole module gets only compiled when testing (see [Rust-Book: Test-Organization](https://doc.rust-lang.org/book/ch11-03-test-organization.html))

2020-11-16 14:52 UTC, heringerp commented on src/formula.rs
> +    if i_maingroup == j_maingroup {
I have trouble understanding how this could be done. I have thought about putting it into `InteractionParameter::from`

2020-11-24 08:51 UTC, sarcaustech commented on src/formula.rs
> +    if i_maingroup == j_maingroup {
Yeah sorry, that's what I meant 🙈  I also thought about this again and conclude that it should stay in `calc_10` so we assume `Psi` and not `a_ij`. 
Cleaned the part from first comment then.

2020-11-24 08:56 UTC, sarcaustech commented on src/formula.rs
> +    Ok(std::f64::consts::E.powf(-interp.a_ij / temperature))
Yes. Created a kanban card

2020-11-24 08:59 UTC, sarcaustech commented on src/formula.rs
> +        let fg = FunctionalGroup::from(*id, 0.0).unwrap();
`unwrap` resolved with changing the input param.

2020-11-24 08:59 UTC, sarcaustech commented on src/calculator.rs
> +    let x_k_map: HashMap<u8, f64> = id_list.clone().into_iter().zip(x_m).collect();
Added as kanban card

2020-11-24 09:10 UTC, merged